import {
    gray,
    mauve,
    slate,
    sage,
    olive,
    sand,
    tomato,
    red,
    crimson,
    pink,
    plum,
    purple,
    violet,
    indigo,
    blue,
    sky,
    mint,
    cyan,
    teal,
    green,
    grass,
    lime,
    yellow,
    amber,
    orange,
    brown,
    bronze,
    gold,
    whiteA,
    blackA,
} from '@radix-ui/colors'

export default {
    ...gray,
    ...mauve,
    ...slate,
    ...sage,
    ...olive,
    ...sand,
    ...tomato,
    ...red,
    ...crimson,
    ...pink,
    ...plum,
    ...purple,
    ...violet,
    ...indigo,
    ...blue,
    ...sky,
    ...mint,
    ...cyan,
    ...teal,
    ...green,
    ...grass,
    ...lime,
    ...yellow,
    ...amber,
    ...orange,
    ...brown,
    ...bronze,
    ...gold,
    ...whiteA,
    ...blackA,

    main1: '$sand1',
    main2: '$sand2',
    main3: '$sand3',
    main4: '$sand4',
    main5: '$sand5',
    main6: '$sand6',
    main7: '$sand7',
    main8: '$sand8',
    main9: '$sand9',
    main10: '$sand10',
    main11: '$sand11',
    main12: '$sand12',

    primary1: '$amber1',
    primary2: '$amber2',
    primary3: '$amber3',
    primary4: '$amber4',
    primary5: '$amber5',
    primary6: '$amber6',
    primary7: '$amber7',
    primary8: '$amber8',
    primary9: '$amber9',
    primary10: '$amber10',
    primary11: '$amber11',
    primary12: '$amber12',

    secondary1: '$indigo1',
    secondary2: '$indigo2',
    secondary3: '$indigo3',
    secondary4: '$indigo4',
    secondary5: '$indigo5',
    secondary6: '$indigo6',
    secondary7: '$indigo7',
    secondary8: '$indigo8',
    secondary9: '$indigo9',
    secondary10: '$indigo10',
    secondary11: '$indigo11',
    secondary12: '$indigo12',

    error1: '$red1',
    error2: '$red2',
    error3: '$red3',
    error4: '$red4',
    error5: '$red5',
    error6: '$red6',
    error7: '$red7',
    error8: '$red8',
    error9: '$red9',
    error10: '$red10',
    error11: '$red11',
    error12: '$red12',

    warn1: '$yellow1',
    warn2: '$yellow2',
    warn3: '$yellow3',
    warn4: '$yellow4',
    warn5: '$yellow5',
    warn6: '$yellow6',
    warn7: '$yellow7',
    warn8: '$yellow8',
    warn9: '$yellow9',
    warn10: '$yellow10',
    warn11: '$yellow11',
    warn12: '$yellow12',

    success1: '$grass1',
    success2: '$grass2',
    success3: '$grass3',
    success4: '$grass4',
    success5: '$grass5',
    success6: '$grass6',
    success7: '$grass7',
    success8: '$grass8',
    success9: '$grass9',
    success10: '$grass10',
    success11: '$grass11',
    success12: '$grass12',

    info1: '$blue1',
    info2: '$blue2',
    info3: '$blue3',
    info4: '$blue4',
    info5: '$blue5',
    info6: '$blue6',
    info7: '$blue7',
    info8: '$blue8',
    info9: '$blue9',
    info10: '$blue10',
    info11: '$blue11',
    info12: '$blue12',
}
